---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- logo:
    icon: fedora.png # optional

- resources:
    cpu: true
    cputemp: true
    memory: true
    disk:
        - /
        - /mnt/sata_sda

- search:
    provider: google
    showSearchSuggestions: true
    target: _blank

- openweathermap:
    label: Lviv # optional
    latitude: 49.8383
    longitude: 24.0232
    units: metric # or imperial
    apiKey: a2aafc1cff434dcbce3daf2217ba2baa
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- datetime:
    text_size: xl
    format:
      timeStyle: short
      hourCycle: h23

# - portainer:
#     url: http://192.168.0.20:9000
#     env: 2
#     key: ptr_Ai9/O5cCn81n2D//SPmTWD2YNCbExdXI2Wm9+6hsHdI=

# - glances:
#     url: http://192.168.0.15:61208
#     # username: user # optional if auth enabled in Glances
#     # password: pass # optional if auth enabled in Glances
#     cpu: true # optional, enabled by default, disable by setting to false
#     info: true
#     mem: true # optional, enabled by default, disable by setting to false
#     cputemp: true # disabled by default
#     uptime: true # disabled by default
#     disk: /boot # disabled by default, use mount point of disk(s) in glances. Can also be a list (see below)
#         # - nvme0n1
#         # - /
#     diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
#     expanded: false # show the expanded view
#     # label: Fedora host # optional